# Generated by Django 4.2.2 on 2023-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menuitem_cuisine_restaurant_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparation', 'In Preparation'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
